import React, {Suspense} from "react";
import Comments from "@/components/Comments";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Comment | Detrator",
  description: "Generated by create next app",
};

const CommentsPage = () => {
  return (
    <>
      <Suspense fallback={"Loading..."}>
        <Comments />
      </Suspense>
    </>
  );
};

export default CommentsPage;
