import React from "react";
import LoginContainer from "@/components/LoginContainer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login | Detrator",
  description: "Generated by create next app",
};

const LoginPage = () => {

  return (
    <>
    <LoginContainer/>
    </>
  );
};

export default LoginPage;
